header = [
    { title = "技术规范", href = "https://spec.matrix.org" },
    { title = "关于", href = "/about/" },
    { title = "博客", href = "/blog/" },
    { title = "文档", href="/docs/" },
    { title = "生态系统", section = "ecosystem" },
    { title = "捐赠", href="/support" },
    { title = "尝试 Matrix", href = "/try-matrix/", primary = true },
]

footer_internal = [
    { title = "捐赠", href = "/support" },
    { title = "商店", href = "https://shop.matrix.org" },
    { title = "安全声明政策", href = "/security-disclosure-policy" },
    { title = "安全名人堂", href = "/security-hall-of-fame" },
    { title = "行为准则", href = "/legal/code-of-conduct" },
    { title = "法律", href = "/legal" },
    { title = "联系方式", href = "/contact" },
    { title = "源码", href = "https://github.com/matrix-org/matrix.org/" },
]

footer_external = [
    { image = "github.svg", alt = "GitHub", href = "https://github.com/matrix-org" },
    { image = "gitlab.svg", alt = "GitLab", href = "https://gitlab.matrix.org/" },
    { image = "mastodon.svg", alt = "Mastodon", href = "https://mastodon.matrix.org/@matrix" },
    { image = "twitter.svg", alt = "Twitter", href = "https://twitter.com/matrixdotorg" },
    { image = "youtube.svg", alt = "YouTube", href = "https://www.youtube.com/channel/UCVFkW-chclhuyYRbmmfwt6w" },
    { image = "rss.svg", alt = "RSS", href = "/atom.xml" },
]
